trigger LegacyBillingItemTrigger on Legacy_Billing_Item__c(before insert, before update, after insert, after update, after delete) {
    
    if (Trigger.isBefore) {
        
        if (Trigger.isInsert) {
            //Populate Departments, Territories & Product Names when using DataLoader.
            LegacyBillingItemServices.populateDimensions(Trigger.new);
            
            //Legacy Billing Items created manually
            LegacyBillingItemServices.updateManuallyCreatedLegacyItem(LegacyBillingItemServices.filterLegacyBillingItem(Trigger.new));
        
            //Legacy Billing Items generated by clicklink.
            LegacyBillingItemServices.updateClickLinkCreatedLegacyItem(LegacyBillingItemServices.filterClickLinkLegacyBillingItem(Trigger.new));
                    
        }
        
        if (Trigger.isUpdate) {
            LegacyBillingItemServices.validationLegaycBillingItems(Trigger.new, Trigger.oldMap);
            
        }
                
    }
    
    if (Trigger.isAfter) {
        if (Trigger.isInsert) {
            LegacyBillingItemServices.generateLegacyBLIForAddidtionalFees(Trigger.new);
            
            //Recalculate Total Commissionable Amount
            LegacyBillingItemServices.updateTotalCommissionableAmount(LegacyBillingItemServices.filteredLegacyItemForTotalCommissionableAmount(Trigger.new));
            
        }
    
        //Recalculate Subtotal & Tax for Legacy Invocies
        if (Trigger.isUpdate) {
            LegacyBillingItemServices.updateAggregatedFieldsOnLegacyProformInvoice(LegacyBillingItemServices.filterLegacyInvoiceForUpdateAggregate(Trigger.oldMap, Trigger.new));
            
            //Recalculate Total Commissionable Amount
            LegacyBillingItemServices.updateTotalCommissionableAmount(LegacyBillingItemServices.filteredLegacyItemForTotalCommissionableAmount(Trigger.new));
        
        }
        
        //Recalculate Subtotal & Tax for Legacy Invocies        
        if (Trigger.isDelete) {
            LegacyBillingItemServices.updateAggregatedFieldsOnLegacyProformInvoice(LegacyBillingItemServices.filterLegacyInvoiceForUpdateAggregate(Trigger.old));
            
            //Recalculate Total Commissionable Amount
            LegacyBillingItemServices.updateTotalCommissionableAmount(LegacyBillingItemServices.filteredLegacyItemForTotalCommissionableAmount(Trigger.old));
            
        }
    
    }
    
}