public with sharing class ReportingBalancesServices {

    public static String REPORTING_BALANCE_ACTUAL = 'Actual';
    public static String CLA_TYPE_PROFIT_AND_LOSS = 'Profit and Loss';
    public static String CLA_TYPE_BALANCE_SHEET = 'Balance Sheet';
    public static String CLA_TRIAL_BALANCE2_INCOME = 'Income';
    public static String CLA_TRIAL_BALANCE2_ACCOUNTS_RECEIVABLE = 'Accounts Receivable';
    public static String CLA_REPORTING_CODE_12100 = '12100'; //MRS-6597
    public static String CLA_TRIAL_BALANCE2_CASH = 'Cash';

}